{{- if not .Values.database.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sorotrail.fullname" . }}-db
  labels:
    {{- include "sorotrail.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "database.url is required when database.existingSecret is not set" .Values.database.url | quote }}
{{- end }}
